# Generated by Django 3.2.25 on 2025-07-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250707_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': [('change_only_yours', 'Can  change  only yours feedbacks'), ('feedback_list', 'Listar  feedback API'), ('feedback_retrieve', 'Reuperar 1 registro  feedback API'), ('feedback_update', 'atualizar 1 registro  feedback API'), ('feedback_partialupdate', 'atualizar parcialmente  feedback API'), ('feedback_create', 'Adicionar feedback API'), ('feedback_delete', 'Deleter  feedback API')]},
        ),
    ]
